FROM alpine:latest

RUN apk add --no-cache ca-certificates curl \
    && curl -L -o /usr/local/bin/gobuster https://github.com/OJ/gobuster/releases/download/v3.1.0/gobuster-linux-amd64.7z \
    && apk add --no-cache p7zip \
    && 7z x /usr/local/bin/gobuster -o/usr/local/bin/ \
    && chmod +x /usr/local/bin/gobuster \
    && rm /usr/local/bin/gobuster

ENTRYPOINT ["gobuster"]
