# Generated by Django 5.2.3 on 2025-07-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='details',
            field=models.TextField(blank=True, help_text='Description professionnelle détaillée du script'),
        ),
    ]
